services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./api:/app
      - ./uploads:/app/uploads
      - ./markdowns:/app/markdowns
    env_file:
      - .env

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./worker:/app

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - BASE_URL=http://api:8000
    volumes:
      - ./app:/app
